from __future__ import annotations

from html import escape
from pathlib import Path

from .checker import CompatibilityReport


def render_html_report(report: CompatibilityReport, title: str = "Open Source Compatibility Report") -> str:
    """Render a self-contained HTML report with no third-party dependencies."""
    rows = []
    for check in report.checks:
        status = check.status.upper()
        rows.append(
            "<tr>"
            f"<td>{escape(check.name)}</td>"
            f"<td>{escape(status)}</td>"
            f"<td>{escape(check.message)}</td>"
            "</tr>"
        )

    checks_html = "\n".join(rows) or (
        '<tr><td colspan="3">No compatibility checks were produced.</td></tr>'
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 980px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }}
    h1 {{ margin-bottom: .25rem; }}
    .score {{ font-size: 2rem; font-weight: 700; margin: 1rem 0 1.5rem; }}
    .meta {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: .75rem; margin-bottom: 1.5rem; }}
    .card {{ border: 1px solid #d0d7de; border-radius: 8px; padding: .85rem; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ border: 1px solid #d0d7de; padding: .7rem; text-align: left; vertical-align: top; }}
    th {{ background: #f6f8fa; }}
    footer {{ margin-top: 2rem; color: #57606a; font-size: .9rem; }}
  </style>
</head>
<body>
  <h1>{escape(title)}</h1>
  <p>Environment compatibility summary generated by Open Source Compatibility.</p>

  <div class="score">Compatibility score: {report.score}%</div>

  <section class="meta">
    <div class="card"><strong>Operating system</strong><br>{escape(report.os)} {escape(report.os_release)}</div>
    <div class="card"><strong>Architecture</strong><br>{escape(report.architecture)}</div>
    <div class="card"><strong>Python</strong><br>{escape(report.python_version)}</div>
  </section>

  <h2>Checks</h2>
  <table>
    <thead>
      <tr><th>Check</th><th>Status</th><th>Details</th></tr>
    </thead>
    <tbody>
      {checks_html}
    </tbody>
  </table>

  <footer>Generated by Open Source Compatibility.</footer>
</body>
</html>
"""


def write_html_report(
    report: CompatibilityReport,
    path: str | Path,
    title: str = "Open Source Compatibility Report",
) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html_report(report, title=title), encoding="utf-8")
    return output_path
